name: dockerized-test

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  dockerized-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: pip
          cache-dependency-path: requirements/dev.txt

      - name: Build the test image
        run: |
          docker build . \
            -t local/test \
            -f Dockerfile.test \
            --build-arg BASE_IMAGE=public.ecr.aws/lambda/python:3.14

      - name: Run dockerized suites
        uses: aws/containerized-test-runner-for-aws-lambda@76eacfb110903739d9c5f7fcdaafede6324a1473 # maxday/client-context
        with:
          suiteFileArray: '["./test/dockerized/suites/*.json"]'
          dockerImageName: 'local/test'
          taskFolder: './test/dockerized/tasks'
